"""add phone number

Revision ID: 314d59141606
Revises: 7e3ae24611d8
Create Date: 2022-03-06 16:18:21.143402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "314d59141606"
down_revision = "7e3ae24611d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
